# Generated by Django 2.2.6 on 2019-10-13 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postdata', '0002_auto_20191013_0407'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table=None,
        ),
    ]
